# Generated by Django 3.2 on 2021-11-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_paid',
            field=models.BooleanField(default=False),
        ),
    ]
