# Generated by Django 3.2 on 2021-11-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211107_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('vendor_paid',)},
        ),
    ]
